### ISSUE TITLE
missing readme

### ISSUE THREAD

**Issue by danielt69** [n2DigitalMedia/contact-form-7-dotmailer#2]
Hi guys,

Can anyone of you please add a basic instruction to the readme file.
I use contact form 7 and have my Dotmailer API user but I don't know how to connect the form to a specific address book...

Can you help me, please?
Thanks in advance

**Comment by WayneHarris** [comment]
Hi @danielt69,

It's a fair point, we do need to get around to adding a read.me so will keep the issue open until we have done this.

But to help you for now. In contact form 7 you need to add a hidden field to your form called "dm_addressbook" with a value of your dotmailer address book id.

Hope this helps.
