### ISSUE TITLE
Throws an error while submitting contact form

### ISSUE THREAD

**Issue by bhuvanrikka** [n2DigitalMedia/contact-form-7-dotmailer#4]
After activating the plugin, I am no longer able to submit the contact form 7. It throws the following error "There was a problem: Call to undefined function _log() ".

Am i supposed to give some permissions?

**Comment by WayneHarris** [comment]
Hi @bhuvanrikka, sorry for the late reply. 

Did you resolve this? It could well be the permission of the plugins etc.

Did you try to do a fresh install of the plugin.

What version of WordPress and ContactForm & are you using?
