### ISSUE TITLE
Does this work with latest releases of WP and Contact Form 7

### ISSUE THREAD

**Issue by AndyRoberts99** [n2DigitalMedia/contact-form-7-dotmailer#5]
Hello

I'm trying to use this plugin but having no luck - all I get is the spinning processing icon from CF7

**Comment by WayneHarris** [comment]
Hi Andy, 

Will need a little more info to try and help you with this.

If you disable the plugin do your CF7 forms work?
Are there any errors in the console log of the browser?
Which version of WordPress and CF7 are you using?

**Comment by AndyRoberts99** [comment]
Hi

I get a 500 Server Error - console says, "There was a problem: Call to undefined function _log()". Disable the plugin and the form works.

Wordpress 4.9 yesterday and 4.9.1 today. CF7 V4.9.91

Hope that helps

**Comment by WayneHarris** [comment]
Hi,

I removed the call to the missing _log() function which should resolve the issue. 

I do not have time to test it this morning, but if you clone the latest master branch and try it will hopefully resolve the problem.

Could you let me know the outcome so I can close the issue if it works for you?

**Comment by AndyRoberts99** [comment]
I've only just got back on to this so will get back to you once I've done this.

**Comment by AndyRoberts99** [comment]
Hello - the new version activates without a problem in WP Admin now - thanks
